atlantis_base_simulator:
  ros__parameters:
    use_sim_time: True
    map: "src/atlantis_collection/scenarios/empty/empty.yaml"
    robots: ["robot1"]
    robot1:
      ID: 1
      type: 1
      initial_pose:
        x: 0.0
        y: 0.0
        z: 0.0
        yaw: 0.0

ecl_fleet_coordination:
  ros__parameters:
    use_sim_time: True
    params:
      origin:
        x: -1.
        y: -1.
      resolution: 0.1
      width: 400
      height: 400
    robots: ["robot1"]
    robot1:
      ID: 1
      type: 2
