atlantis_base_simulator:
  ros__parameters:
    use_sim_time: True
    goal_tolerance: 2.0
    scenario: "mine"
    map: "mine_small.yaml"
    lattice_primitives: "a25"
    primitives_dir: "/home/pofe/ecceleron_ros2_ws/src/ecceleron_ros2/navigation/ecceleron_global_planner/lattice_primitives/Volvo_A25/"
    robots: ["robot1", "robot2"]
    max_planning_time: 20.0
    use_precomputed_paths: False
    precomputed_paths_folder: "/home/pofe/atlantis_ws/src/atlantis/atlantis_collection/scenarios/mine/paths"
    #max_sim_time: 5.0
    materials: ["mat1", "mat2"]
    waypoints_file: "mine1_waypoints.txt"
    #waypoints: ["wp1" , "wp2" ,"wp3", "wp4"]
    metrics: ["computational_time" , "path_length"]
    refilling: True
    use_trajectory_dt: true
    dt: 0.1
    real_time_factor: 10.
    robot1:
      ID: 1
      type: 2
      capacity: 10.0
      minimum_turning_radius: 8.0
      model: "package://atlantis_collection/models/mine_truck.stl"
      footprint: "[[1.0, -1.0], [1.0, 1.0], [-1.0, 1.0], [-1.0, -1.0]]"
      planner: "Hybrid"
      initial_pose:
        x: 40.01
        y: 116.76
        z: 0.0
        yaw: 2.59
    robot2:
      ID: 2
      type: 2
      capacity: 10.0
      minimum_turning_radius: 8.0
      model: "package://atlantis_collection/models/mine_truck.stl"
      footprint: "[[1.0, -1.0], [1.0, 1.0], [-1.0, 1.0], [-1.0, -1.0]]"
      planner: "Hybrid"
      initial_pose:
        x: 92.4025
        y: 100.254
        z: 0.0
        yaw: -0.572064
    mat1:
      locations: ["load1", "load2","load8"]
      load1:
        amount: 10.0
      load2:
        amount: 10.0
      load8:
        amount: 10.0

ecl_atlantis_base_simulator:
  ros__parameters:
    use_sim_time: True
    goal_tolerance: 2.0
    map: /home/pofe/atlantis_ws/src/atlantis/atlantis_collection/scenarios/mine/mine_small.yaml
    lattice_primitives: "a25"
    primitives_dir: "/home/pofe/ecceleron_ros2_ws/src/ecceleron_ros2/navigation/ecceleron_global_planner/lattice_primitives/Volvo_A25/"
    robots: ["robot1", "robot2"]
    max_planning_time: 5.0
    use_precomputed_paths: False
    precomputed_paths_folder: "/home/pofe/atlantis_ws/src/atlantis/atlantis_collection/scenarios/mine/paths"
    #max_sim_time: 5.0
    materials: ["mat1", "mat2"]
    waypoints_file: "mine1_waypoints.txt"
    #waypoints: ["wp1" , "wp2" ,"wp3", "wp4"]
    metrics: ["computational_time" , "path_length"]
    refilling: True
    use_trajectory_dt: true
    dt: 0.1
    real_time_factor: 10.
    robot1:
      ID: 1
      type: 1
      capacity: 10.0
      minimum_turning_radius: 8.0
      model: "package://atlantis_collection/models/mine_truck.stl"
      footprint: "[[1.0, -1.0], [1.0, 1.0], [-1.0, 1.0], [-1.0, -1.0]]"
      planner: "Lattice"
      initial_pose:
        x: 40.01
        y: 116.76
        z: 0.0
        yaw: 2.59
    robot2:
      ID: 2
      type: 1
      capacity: 10.0
      minimum_turning_radius: 8.0
      model: "package://atlantis_collection/models/mine_truck.stl"
      footprint: "[[1.0, -1.0], [1.0, 1.0], [-1.0, 1.0], [-1.0, -1.0]]"
      planner: "Lattice"
      initial_pose:
        x: 92.4025
        y: 100.254
        z: 0.0
        yaw: -0.572064
    mat1:
      locations: ["load1", "load2","load8"]
      load1:
        amount: 10.0
      load2:
        amount: 10.0
      load8:
        amount: 10.0

ecl_fleet_coordination:
  ros__parameters:
    use_sim_time: True
    params:
      origin:
        x: -1.
        y: -1.
      resolution: 0.1
      width: 400
      height: 400
    robots: ["robot1", "robot2"]
    robot1:
      ID: 1
      type: 2
    robot2:
      ID: 2
      type: 2

atlantis_simple_commander:
   ros__parameters:
    use_sim_time: True
    robot_ids: [1,2]
    actions: ["MoveTo", "Load", "Dump"]

state_generator:
  ros__parameters:
    state_generator_plugin: "PDDL"
    PDDL:
      plugin: "atlantis_state::PddlStateGenerator"
