atlantis_base_simulator:
  ros__parameters:
    use_sim_time: True
    goal_tolerance: 2.0
    scenario: "mine"
    map: "mine_small.yaml"
    lattice_primitives: "volvo_l70_cardinality3"
    primitives_dir: "src/ecceleron_ros2/navigation/ecceleron_global_planner/lattice_primitives/Volvo_L70/"
    robots: ["robot1", "robot2"]
    max_planning_time: 20.0
    randomness: True
    use_precomputed_paths: True
    precomputed_paths_folder: "/home/pofe/atlantis_ws/src/atlantis/atlantis_collection/scenarios/mine/paths"
    #max_sim_time: 5.0
    materials: ["mat1", "mat2", "mat3", "mat4", "mat5"]
    waypoints_file: "mine1_waypoints.txt"
    #waypoints: ["wp1" , "wp2" ,"wp3", "wp4"]
    metrics: ["computational_time" , "path_length"]
    refilling: True
    use_trajectory_dt: true
    dt: 0.1
    real_time_factor: 10.
    robot1:
      ID: 1
      type: 2
      capacity: 10.0
      minimum_turning_radius: 8.0
      #model: "package://turtlebot3_description/meshes/bases/burger_base.stl"
      footprint: "[[1.0, -1.0], [1.0, 1.0], [-1.0, 1.0], [-1.0, -1.0]]"
      planner: "Hybrid"
      initial_pose:
        x: 93.8028 
        y: 8.59434
        z: 0.0
        yaw: -0.847167
    robot2:
      ID: 2
      type: 2
      capacity: 10.0
      minimum_turning_radius: 8.0
      #model: "package://turtlebot3_description/meshes/bases/burger_base.stl"
      footprint: "[[1.0, -1.0], [1.0, 1.0], [-1.0, 1.0], [-1.0, -1.0]]"
      planner: "Hybrid"
      initial_pose:
        x: 93.8028 
        y: 8.59434
        z: 0.0
        yaw: -0.847167
    mat1:
      locations: ["load1"]
      load1:
        amount: 10.0
    mat2:
      locations: ["load2"]
      load2:
        amount: 10.0
    mat3:
      locations: ["load3"]
      load3:
        amount: 10.0
    mat4:
      locations: ["load4"]
      load4:
        amount: 10.0
    mat5:
      locations: ["load5"]
      load5:
        amount: 10.0

ecl_fleet_coordination:
  ros__parameters:
    use_sim_time: True
    params:
      origin:
        x: -1.
        y: -1.
      resolution: 0.1
      width: 400
      height: 400
    robots: ["robot1", "robot2"]
    robot1:
      ID: 1
      type: 2
    robot2:
      ID: 2
      type: 2

atlantis_simple_commander:
   ros__parameters:
    use_sim_time: True
    robot_ids: [1,2]
    actions: ["MoveTo", "Load", "Dump"]

state_generator:
  ros__parameters:
    state_generator_plugin: "PDDL"
    PDDL:
      plugin: "atlantis_state::PddlStateGenerator"
